### ISSUE TITLE
Add API docs

### ISSUE THREAD

**Issue by Dr-Electron** [iota-wiki/iota-wiki#401]
**Describe the solution you'd like**

Add APIs description to wiki:
https://editor.swagger.io/?url=https://raw.githubusercontent.com/iotaledger/chronicle.rs/main/docs/api.yaml
https://editor.swagger.io/?url=https://raw.githubusercontent.com/rufsam/protocol-rfcs/master/text/0026-rest-api/0026-rest-api.yaml

**Additional context**
This PR should be useful: https://github.com/facebook/docusaurus/issues/638

**Comment by jlvandenhout** [comment]
Fixed by #833
