### ISSUE TITLE
Move to new Github organization

### ISSUE THREAD

**Issue by Dr-Electron** [iota-wiki/iota-wiki#471]
### Discussed in https://github.com/iota-community/iota-wiki/discussions/460

<div type='discussions-op-text'>

<sup>Originally posted by **Dr-Electron** February 11, 2022</sup>
The Wiki with the latest developments is going to be way more than just a wiki. We may have own plugins, own themes, own tutorials, own videos and so on.
So it may make sense to move away from the iota-community repo.
Wdyt?
And if we do that, what should be the name of the new org?</div>

**Comment by jlvandenhout** [comment]
Hello from the future. We moved to https://github.com/iota-wiki/iota-wiki.
