### ISSUE TITLE
Docs Update: Participate

### ISSUE THREAD

**Issue by charlesthompson3** [iota-wiki/iota-wiki#494]
**Is your feature request related to a problem? Please describe.**
With the upcoming changes, some articles in the documentation may require updates and versioning.

**Describe the solution you'd like**
We need to be able to launch products with their respective docs to improve the overall developer experience.

To accomplish this, the following pages may require updating. Please feel free to add or remove any items you see fit.

- About nodes
- Become a node operator
- Node software
- Community links
- All products listed in frameworks

**Additional context**
To what extent I can, I would create a PR for these updates, but the @iotaledger/tech-writers team will require support from the developers to know exactly what should be updates.

For further reference, see the parent issue link: https://github.com/iotaledger/stardust-project/issues/45

**Comment by jlvandenhout** [comment]
@lucas-tortora @aleksei-korolev Could you indicate if you want to keep this around for now as a reminder of if we can close?

**Comment by lucas-tortora** [comment]
> @lucas-tortora @aleksei-korolev Could you indicate if you want to keep this around for now as a reminder of if we can close?


I think we can close directly, a lot has happened since this was created.

**Comment by jlvandenhout** [comment]
Closed as not relevant anymore.
