### ISSUE TITLE
High CPU load on the landing page

### ISSUE THREAD

**Issue by aleksei-korolev** [iota-wiki/iota-wiki#635]
**Describe the bug**

When I visit wiki.iota.org, I experience a high cpu load (100% of a single core) on my laptop and my PC. 

**To Reproduce**

1. Go to wiki.iota.org
2. Open a resource monitor of your choice.

**Expected behavior**

It just works.

**Desktop (please complete the following information):**

- OS: Manjaro
- Browser: Firefox
- Version: 97.0.1 (64-bit) and 102.0.1 (64-bit)

**Additional context**
Happens after we have update the landing page.

**Comment by Dr-Electron** [comment]
@JSto91 do we want to close it and just buy a new laptop for @aleksei-korolev ?

**Comment by JSto91** [comment]
> @JSto91 do we want to close it and just buy a new laptop for @aleksei-korolev ?

😆 we can close it for now if you want - i just let it open to not forget it later on. I'll just add a task in the todo

**Comment by Dr-Electron** [comment]
No, we can leave it open. Maybe you should explain here what you still want to try tho. So we don't loose track of the solutions we possibly still want to try 🤔

**Comment by aleksei-korolev** [comment]
> @JSto91 do we want to close it and just buy a new laptop for @aleksei-korolev ?

FYI :trollface:

![image](https://user-images.githubusercontent.com/42579543/185907277-96a9c9a5-5120-4de7-8835-d701cc5c2ff5.png)

**Comment by JSto91** [comment]
Ups, yeah so one thing i would like it try is to redesign/animate the bots as Lottie's. Unfortunatly the App i want to try that with is still in closed beta, so not possible yet, but hopefully soon :trollface:
