### ISSUE TITLE
Define Test and Devnet

### ISSUE THREAD

**Issue by Dr-Electron** [iota-wiki/iota-wiki#660]
**Describe the solution you'd like**

We should define what Testnets and Devnets are and how they differ [here](https://wiki.iota.org/networks/testnets)

Something like:
Testnet: Network with worthless token. New features that aren’t on any other network yet
Devnet: Network with worthless token. Mirror of production networks (Shimmer/IOTA) for devs to develop on

**Comment by annie101101046** [comment]
Current status:
When clicking `network`, it will direct me to [IOTA 1.5 Chrysalis ](https://wiki.iota.org/networks/iota-1.5-chrysalis). 

Potential onboarding experience: 
However, I think we need to add one more section at the beginning and be clear in explaining our network stage and definition, including:
1) We have 3 stages: Testnet -> Shimmer -> IOTA  
2) The difference of Testnet vs Devnet

Also, the structure of the current network section needs a better order. Maybe can be:

- Network Overview (Network token migration can be put in this section)
- Testnet 
- Devnet 
- IOTA 1.5 
- IOTA 2.0 
- Protocol (Including Chrysalis and Stardust)
<img width="294" alt="截圖 2022-07-25 下午4 20 24" src="https://user-images.githubusercontent.com/11192870/180731657-26476eae-2f42-423e-a728-495b8bc8232e.png">

Also, I am wondering if we can put `Shimmer` in the network navbar? currently we put shimmer in [here](https://wiki.iota.org/introduction/develop/reference/networks/shimmer)

The user journey will be:
Click Network -> Click Stardust -> Click Reference ->  Click Networks -> Click Shimmer Beta / Shimmer

It's a little bit hard to find the Shimmer content from my point of view.

**Comment by Dr-Electron** [comment]
> Also, I am wondering if we can put Shimmer in the network navbar? currently we put shimmer in [here](https://wiki.iota.org/introduction/develop/reference/networks/shimmer)

100%. The problem is: The stardust docs are [external ones](https://github.com/iotaledger/introduction-docs/tree/develop). So imo we should ditch the current [Chrysalis](https://wiki.iota.org/networks/iota-1.5-chrysalis) section and just have a small introduction page for networks. Maybe something like Jeroen created [here](https://github.com/iota-community/iota-wiki/pull/658)

**Comment by Dr-Electron** [comment]
Lucas also mentioned that for most people testnet and devnet are the same thing. So betanet could be a possibility for the Shimmer Beta :trollface:

**Comment by Dr-Electron** [comment]
Would be interesting to get some opinions from engineering. @luca-moser

**Comment by jlvandenhout** [comment]
> Maybe something like Jeroen created [here](https://github.com/iota-community/iota-wiki/pull/658)

Totally agree with the combination of what you and @annie101101046 are suggesting here. Reorder the networks in the sidebar and provide an overview page with a short introduction of production, test and devnets and which networks belong in which category.

**Comment by luca-moser** [comment]
My personal opinion is that the DevNet itself brings no value and will be decommissioned and replaced by the Public Testnet (what comms calls Shimmer Beta network). So it would be great to mention somewhere that that network is subject to being removed in the future and projects should migrate to/build on the Public Testnet.

**Comment by annie101101046** [comment]
Regarding the `devnet` vs `testnet` , I just want to double-check the consensus here.

**Last time the discussion was:** 
We should have one public testnet and that’s it (no more devnet, only one public testnet)

**What's next**
- We add one more section at the beginning and be clear in explaining our network stage and definition:
We have 3 stages: `Testnet -> Shimmer -> IOTA` (Our version drop-down will map this as well)
- Remove the Devnet term that confused the readers


@luca-moser Do you mind helping check if this is ok that we could move to the next stage?

**Comment by annie101101046** [comment]
Below are what we've confirmed so far:

-  If we are just talking about content, it would be fine to just list testnet, Shimmer, and IOTA. The devnet is just a mirror of the mainnet, so it doesn't have its own version.

**What's next**
- We add one more section at the beginning and be clear in explaining our network stage and definition: we have 3 stages: Testnet -> Shimmer -> IOTA (Our version drop-down will map this as well)
- Remove the Devnet term that confused the readers
-  Leave an Ione page until it's alive there saying here are the API endpoints plus the faucet
