### ISSUE TITLE
Update Search Indexes On Deploy

### ISSUE THREAD

**Issue by lucas-tortora** [iota-wiki/iota-wiki#689]
**Describe the bug**

Algolia search indexes don't seem to be updated after every deploy.  This leads to dead results as well not finding articles which are in the wiki.

**To Reproduce**

1. Search for "seed and addresses"
2. Click on the first result

**Expected behavior**
The search bar indexes should contain every article in the wiki, and nothing else.

**Screenshots**

![image](https://user-images.githubusercontent.com/85233773/182636364-504baee0-3515-4fa6-a3e4-d500983692c7.png)

**While we're at it**

It'd be great if we can get the preview of the search results to show their:

1. Navbar section
2. (if applicable) The project the results is from
3. It's top level sidebar element.

**Comment by jlvandenhout** [comment]
I don't have full access to our Algolia dashboard. I can only see the crawler runs weekly and from the Algolia page I get as open source project we can do 2 million index operations a month, but I can't really find what counts as one operation.

Triggering a crawl on every successful build would be ideal I guess, but I'm not sure if that is feasible with our current plan. Could you find out?

**Comment by lucas-tortora** [comment]
> I don't have full access to our Algolia dashboard. I can only see the crawler runs weekly and from the Algolia page I get as open source project we can do 2 million index operations a month, but I can't really find what counts as one operation.
> 
> Triggering a crawl on every successful build would be ideal I guess, but I'm not sure if that is feasible with our current plan. Could you find out?

It seems we've got a crawler config now :) , with any luck I just configured it to run daily at midnight. I'll check on it tomorrow

https://github.com/iota-community/iota-wiki/issues/689#issuecomment-1222717912

**Comment by Dr-Electron** [comment]
We could even trigger the crawler in our deploy action. So if we ever change our deploy times it won't mismatch again. But @jlvandenhout can tell us more about that
