### ISSUE TITLE
Check that the build system is not contributing to analytics.

### ISSUE THREAD

**Issue by aleksei-korolev** [iota-wiki/iota-wiki#699]
**Describe the bug**

We know that the old build system runs were counted by Matomo analytics, which resulted in a 50% bounce rate across the wiki. After the new system had been introduced, the bounce rate dropped to 5-8%.

We, however, do not know if the new build system has left the analytics alone or if it still spoils it but in a lesser degree. 

**To Reproduce**

I don't know.

**Expected behavior**

The build system is not contributing data to our analytics.

**Comment by jlvandenhout** [comment]
Could you elaborate on what is needed? I don't think we have any analytical knowledge on the Wiki team side, so we wouldn't know what to look for or what the expected result is.

**Comment by aleksei-korolev** [comment]
@jlvandenhout does our build pipeline visit the deployed pages during the run? Because before it did, which totally scrambled our bounce rate stats. The question is if we resolved it completely or the pipeline, for example, gives us an extra thousand views every month.

I guess one way to check is to look at the code. The other way to check would be deploying the wiki on a separate url with separate analytics, run a hundred builds and see how analytics look like without actual visitors.

**Comment by jlvandenhout** [comment]
No, the build doesn't. The Algolia crawler does though, to build the search index. That's the only thing I can think of that automatically visits webpages from our side.

**Comment by aleksei-korolev** [comment]
@jlvandenhout @Dr-Electron could you check if Matomo is set up properly? I don't have access to these settings.

https://matomo.org/faq/how-to/faq_17483/

**Comment by Dr-Electron** [comment]
I will have a look this weekend hopefully

**Comment by Dr-Electron** [comment]
If there are no concerns about this anymore any my above changes fix it, I think we can close this.
Feel free to open another issue if you thinks it doesn't work
