### ISSUE TITLE
NavBar UX

### ISSUE THREAD

**Issue by aleksei-korolev** [iota-wiki/iota-wiki#709]
On desktop, it is not obvious that you can also click foldable navbar items, not just the menu items. Especially with the nodes, where it is easy to think that you are choosing between "Bee" and "Hornet", while "Nodes" itself is also an option. This is probably because the navbar entries are not highlighted in the same way as menu items are. Or maybe we should duplicate the entries in their menus, e. g.

```
Nodes
- Nodes
- Bee
- Hornet
```

On mobile it's even worse. You can't click foldable navmenu entries, it's just folds and unfold them. You have to long-press them and copy the link. I don't think anyone does that.

**Comment by Dr-Electron** [comment]
I think we should duplicate the entries in the menu. That's the most clear approach imo

**Comment by Dr-Electron** [comment]
As we are not using dropdown anymore this can be closed
