### ISSUE TITLE
Local Development in README not complete

### ISSUE THREAD

**Issue by antonionardella** [iota-wiki/iota-wiki#727]
**Describe the bug**
The instructions for Local Development are not complete

**To Reproduce**

1. Follow the README to start local development
2. Follow instructions without prior knowledge about how yarn works
3. Get stuck

**Expected behavior**
A clear and concise description of how to get it to work.

**Comment by jlvandenhout** [comment]
What went wrong exactly? Did you have a look at the prerequisites? Anything we should add to make it more clear to the reader that those prerequisites, especially modern yarn, are needed to continue with local development?

**Comment by jlvandenhout** [comment]
Looking at your associated PR it looks like you ran into a dependency issue, which is best fixed by adding the missing package as a dependency. But I can't seem to reproduce this though. `require-glob` is included in the `content` subdirectory.

**Comment by antonionardella** [comment]
I reproduced it by following the steps in the README blindly

https://pastebin.com/dyAErMVw

What did I miss?

**Comment by antonionardella** [comment]
Issue can be closed.

Layer 8 issue.
