### ISSUE TITLE
Redirects between the Shimmer and Mainnet version of the wiki often return a 404 error

### ISSUE THREAD

**Issue by Raikzer** [iota-wiki/iota-wiki#781]
**Describe the bug**
One example page where this appears:
Go to https://wiki.iota.org/shimmer/iota.rs/libraries/nodejs/references/api_ref and switch to the IOTA version

**To Reproduce**

1. Go to https://wiki.iota.org/shimmer/iota.rs/libraries/nodejs/references/api_ref
2. Switch to IOTA mainnet version

**Expected behavior**
Should redirect to an existing page

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Thorium AVX2
- Version M108.0.5314.0

Potential fix:
As a quick fix we could add a fallback redirect to the start page of the according wiki version

**Comment by Dr-Electron** [comment]
Not sure if your quick fix is that easy to add. When do you redirect to the landing page and when would you need to redirect to the actual 404 page? 🤔 
@jlvandenhout the nicest thing would actually be if you could configure this somehow. Maybe we can even interfere the process and check the path ourselves to redirect to at least a Shimmer 404? 🤔

**Comment by jlvandenhout** [comment]
Yup, we need to at least get to the other environment first, before we can redirect in a useful way. It's one of the drawbacks of having different Docusaurus builds. I will investigate solutions for this as the current state of redirects is very much unwelcome.

**Comment by Dr-Electron** [comment]
We now redirect to a link with relevant search results, but @jlvandenhout proposes the following:
"Instead we should fall back to a page higher up in the page tree, to at least remain in the target environment, as well as remaining close to the original topic."

But not sure how that could be implemented 🤔
