### ISSUE TITLE
Broken links on the Stronghold Welcome page (Shimmer+IOTA)

### ISSUE THREAD

**Issue by chrisgitiota** [iota-wiki/iota-wiki#860]
All links in the first section of the [Stronghold Welcome page](https://wiki.iota.org/shimmer/stronghold.rs/welcome/) lead to a _Page Not Found_ page.

This applies to the Shimmer and IOTA versions of the page.

The links in the following sections (_3rd Party Independent Security Audit_, ...) are OK.

**Comment by Dr-Electron** [comment]
Should be solved with those merged PRs
